inst_Items = {
	{ item_instance = "gold", 						friendly_name = "Мешок монет"	 	},
	{ item_instance = "itar_ranger_addon",			friendly_name = "Броня кольца воды"					},
	{ item_instance = "itmi_sextant", 				friendly_name = "Секстант" 							},
	{ item_instance = "itmi_gold", 					friendly_name = "Золото" 							},
	{ item_instance = "itmi_oldcoin", 				friendly_name = "Старая монета"						},
	{ item_instance = "itmi_bloodcup_mis", 			friendly_name = "Кровавый кубок" 					},
	{ item_instance = "itmi_broom", 				friendly_name = "Метла"								},
	{ item_instance = "itmi_brush", 				friendly_name = "Щетка" 							},
	{ item_instance = "itmi_hammer", 				friendly_name = "Молоток" 							},
	{ item_instance = "itmi_pliers", 				friendly_name = "Щипцы" 							},
	{ item_instance = "itmi_pocket", 				friendly_name = "Кожаный кошелек(внутри 10 з.)"	},
	{ item_instance = "itmi_packet", 				friendly_name = "Пакет" 							},
	{ item_instance = "itmi_silverplate", 			friendly_name = "Серебрянная тарелка"				},
	{ item_instance = "itmi_goldplate", 			friendly_name = "Золотая тарелка"					},
	{ item_instance = "itmi_silvercup", 			friendly_name = "Серебрянный кубок" 				},
	{ item_instance = "itsc_pallight", 				friendly_name = "Свиток света" 						},
	{ item_instance = "itmi_goldcup", 				friendly_name = "Золотой кубок" 					},
	{ item_instance = "itmi_silverring", 			friendly_name = "Серебрянное кольцо" 				},
	{ item_instance = "itmi_goldring", 				friendly_name = "Золотое кольцо" 					},
	{ item_instance = "itmi_silvercandleholder", 	friendly_name = "Серебрянный подсвечник"			},
	{ item_instance = "itmi_goldcandleholder",		friendly_name = "Золотой подсвечник"				},
	{ item_instance = "itmi_silvernecklace", 		friendly_name = "Серебрянное ожерелье" 				},
	{ item_instance = "itmi_goldnecklace", 			friendly_name = "Золотое ожерелье" 					},
	{ item_instance = "itmi_eddasstatue", 			friendly_name = "Статуэтка Инноса" 					},
	{ item_instance = "itmi_ultharsholywater_mis", 	friendly_name = "Святая вода Ультара" 				},
	{ item_instance = "itmi_lute", 					friendly_name = "Лютня" 							},
	{ item_instance = "itmi_pan", 					friendly_name = "Сковорода" 						},
	{ item_instance = "itmi_panfull", 				friendly_name = "Полная сковорода" 					},
	{ item_instance = "itmi_scoop", 				friendly_name = "Ложка" 							},
	{ item_instance = "itmi_saw", 					friendly_name = "Пила" 								},
	{ item_instance = "itmi_rake", 					friendly_name = "Грабли" 							},
	{ item_instance = "itmi_stompler", 				friendly_name = "Толкушка" 							},
	{ item_instance = "itmiswordraw", 				friendly_name = "Сырая сталь" 						},
	{ item_instance = "itmiswordrawhot",			friendly_name = "Нагретая сталь" 					},
	{ item_instance = "itmiswordblade", 			friendly_name = "Острая заготовка"					},
	{ item_instance = "itmiswordbladehot", 			friendly_name = "Остроая нагретая заготовка"		},
	{ item_instance = "itmi_innoseye_broken_mis", 	friendly_name = "Глаз Инноса(неактивен)" 			},
	{ item_instance = "itmi_innoseye_mis", 			friendly_name = "Глаз Инноса" 						},
	{ item_instance = "itmi_joint", 				friendly_name = "Косяк болотника" 					},
	{ item_instance = "itmi_pith", 					friendly_name = "Смола"								},
	{ item_instance = "itmi_sulfur", 				friendly_name = "Сера" 								},
	{ item_instance = "itmi_aquamarine", 			friendly_name = "Аквамарин" 						},
	{ item_instance = "itmi_rockcrystal", 			friendly_name = "Горный хрусталь" 					},
	{ item_instance = "itmi_coal", 					friendly_name = "Уголь" 							},
	{ item_instance = "itmi_quartz", 				friendly_name = "Кварц" 							},
	{ item_instance = "itmi_apfeltabak", 			friendly_name = "Яблочный табак" 					},
	{ item_instance = "itmi_honigtabak", 			friendly_name = "Медный табак" 						},
	{ item_instance = "itmi_flask", 				friendly_name = "Мензурка" 							},
	{ item_instance = "itmi_nugget", 				friendly_name = "Кусок руды" 						},
	{ item_instance = "itat_undeaddragonsoulstone", friendly_name = "Камень души дракона-нежить"	 	},
	{ item_instance = "itat_demonheart", 			friendly_name = "Сердце демона"						},
	{ item_instance = "itat_icegolemheart", 		friendly_name = "Сердце ледянного голема" 			},
	{ item_instance = "itat_firegolemheart", 		friendly_name = "Сердце огненного голема" 			},
	{ item_instance = "itat_stonegolemheart", 		friendly_name = "Сердце каменного голема" 			},
	{ item_instance = "itat_firedragonheart", 		friendly_name = "Сердце огненного дракона"			},
	{ item_instance = "itat_icedragonheart", 		friendly_name = "Сердце ледянного дракона" 			},
	{ item_instance = "itat_rockdragonheart", 		friendly_name = "Сердце каменного дракона"			},
	{ item_instance = "itat_swampdragonheart", 		friendly_name = "Сердце болотного дракона" 			},
	{ item_instance = "itat_dragonegg_mis", 		friendly_name = "Яйцо дракона" 						},
	{ item_instance = "itat_dragonscale", 			friendly_name = "Чешуя дракона"						},
	{ item_instance = "itat_dragonblood", 			friendly_name = "Кровь дракона"						},
	{ item_instance = "itat_skeletonbone", 			friendly_name = "Кость скелета" 					},
	{ item_instance = "itat_goblinbone", 			friendly_name = "Кость гоблина"						},
	{ item_instance = "itat_sheepfur",				friendly_name = "Шкура овцы" 						},
	{ item_instance = "itat_talbinslurkerskin", 	friendly_name = "Шкура кабана"	 					},
	{ item_instance = "itat_wolffur", 				friendly_name = "Шкура волка" 						},
	{ item_instance = "itat_wargfur", 				friendly_name = "Шкура варга" 						},
	{ item_instance = "itat_sharkskin", 			friendly_name = "Шкура болотной акулы" 				},
	{ item_instance = "itat_shadowfur", 			friendly_name = "Шкура мракориса"	 				},
	{ item_instance = "itat_trollblackfur", 		friendly_name = "Шкура черного тролля" 				},
	{ item_instance = "itat_trollfur", 				friendly_name = "Шкура тролля" 						},
	{ item_instance = "itat_addon_keilerfur", 		friendly_name = "Шкура кабана" 						},
	{ item_instance = "itat_trolltooth", 			friendly_name = "Клыки тролля" 						},
	{ item_instance = "itat_waranfiretongue", 		friendly_name = "Язык огненного варана" 			},
	{ item_instance = "itat_claw", 					friendly_name = "Когти" 							},
	{ item_instance = "itat_lurkerclaw", 			friendly_name = "Когти луркера" 					},
	{ item_instance = "itat_lurkerskin", 			friendly_name = "Шкура луркера" 					},
	{ item_instance = "itat_teeth", 				friendly_name = "Зубы" 								},
	{ item_instance = "itat_sharkteeth", 			friendly_name = "Зубы болотной акулы" 				},
	{ item_instance = "itat_meatbugflesh", 			friendly_name = "Мясо жука"	 						},
	{ item_instance = "itat_bugmandibles", 			friendly_name = "Жвала полевого жука"	 			},
	{ item_instance = "itat_crawlermandibles", 		friendly_name = "Жвала ползуна"		 				},
	{ item_instance = "itat_crawlerplate", 			friendly_name = "Панцирь ползуна"			 		},
	{ item_instance = "itat_wing", 					friendly_name = "Крыло" 							},
	{ item_instance = "itat_sting", 				friendly_name = "Жало"	 							},
	{ item_instance = "itat_shadowhorn", 			friendly_name = "Рог мракориса" 					},
	{ item_instance = "itat_drgsnapperhorn", 		friendly_name = "Рог драконнего снеппера"			},
	{ item_instance = "itfo_bacon", 				friendly_name = "Бекон" 							},
	{ item_instance = "itfomuttonraw", 				friendly_name = "Сырое мясо" 						},
	{ item_instance = "itfomutton", 				friendly_name = "Жареное мясо"	 					},
	{ item_instance = "itfo_sausage", 				friendly_name = "Колбаса" 							},
	{ item_instance = "itfo_fish", 					friendly_name = "Рыба" 								},
	{ item_instance = "itfo_fishsoup", 				friendly_name = "Уха"		 						},
	{ item_instance = "itfo_stew", 					friendly_name = "Похлебка" 							},
	{ item_instance = "ifto_xpstew", 				friendly_name = "Рагу из мясных жуков" 				},
	{ item_instance = "itfo_coragonsbeer", 			friendly_name = "Пиво Корагона"			 			},
	{ item_instance = "itfo_beer", 					friendly_name = "Пиво" 								},
	{ item_instance = "itfo_wine", 					friendly_name = "Вино" 								},
	{ item_instance = "itfo_booze", 				friendly_name = "Джин" 								},
	{ item_instance = "itfo_water", 				friendly_name = "Вода" 								},
	{ item_instance = "itfo_cheese", 				friendly_name = "Сыр" 								},
	{ item_instance = "itfo_apple", 				friendly_name = "Яблоко" 							},
	{ item_instance = "itam_strg_01", 				friendly_name = "Амулет силы" 						},
	{ item_instance = "itam_dex_01", 				friendly_name = "Амулет ловкости"					},
	{ item_instance = "itam_hp_01", 				friendly_name = "Амулет здоровья"					},
	{ item_instance = "itam_dex_strg_01", 			friendly_name = "Амулет мощи" 						},
	{ item_instance = "itam_mana_01", 				friendly_name = "Амулет магии" 						},
	{ item_instance = "itam_hp_mana_01", 			friendly_name = "Амулет духовности"	 				},
	{ item_instance = "itam_prot_blackeye_mis", 	friendly_name = "Амулет призыва души" 				},
	{ item_instance = "itam_mana_angar_mis", 		friendly_name = "Магический амулет Ангара" 			},
	{ item_instance = "itam_amulettofdeath_mis",	friendly_name = "Аура Инноса" 						},
	{ item_instance = "itam_prot_fire_01", 			friendly_name = "Амулет огня" 						},
	{ item_instance = "itam_prot_edge_01", 			friendly_name = "Амулет мастерства" 				},
	{ item_instance = "itam_prot_point_01", 		friendly_name = "Амулет каменной кожи"				},
	{ item_instance = "itam_prot_mage_01", 			friendly_name = "Амухет духовной силы"				},
	{ item_instance = "itam_prot_total_01", 		friendly_name = "Амулет защиты от магии"	 		},
	{ item_instance = "itri_prot_fire_01", 			friendly_name = "Кольцо защиты от огня" 			},
	{ item_instance = "itri_prot_fire_02", 			friendly_name = "Кольцо защиты от огня"				},
	{ item_instance = "itri_prot_point_01", 		friendly_name = "Кольцо каменной кожи"		 		},
	{ item_instance = "itri_prot_point_02", 		friendly_name = "Кольцо каменной кожи" 				},
	{ item_instance = "itri_prot_edge_01", 			friendly_name = "Кольцо железной кожи" 				},
	{ item_instance = "itri_prot_edge_02", 			friendly_name = "Кольцо защиты от магии" 			},
	{ item_instance = "itri_prot_mage_01", 			friendly_name = "Кольцо духа"	 					},
	{ item_instance = "itri_prot_mage_02", 			friendly_name = "Кольцо защиты от магии"			},
	{ item_instance = "itri_prot_total_01", 		friendly_name = "Кольцо победы"					 	},
	{ item_instance = "itri_prot_total_02", 		friendly_name = "Кольцо защиты"			 			},
	{ item_instance = "itri_dex_01", 				friendly_name = "Кольцо ловкости" 					},
	{ item_instance = "itri_dex_02", 				friendly_name = "Кольцо ловкости"	 				},
	{ item_instance = "itri_str_01", 				friendly_name = "Кольцо силы"	 					},
	{ item_instance = "itri_str_02", 				friendly_name = "Кольцо силы"	 					},
	{ item_instance = "itri_mana_01", 				friendly_name = "Кольцо маны"	 					},
	{ item_instance = "itri_mana_02", 				friendly_name = "Кольцо маны" 						},
	{ item_instance = "itri_hp_01", 				friendly_name = "Кольцо жизненной силы"				},
	{ item_instance = "itri_hp_02", 				friendly_name = "Кольцо жизненной силы"				},
	{ item_instance = "itri_hp_mana_01", 			friendly_name = "Кольцо здоровья"	 				},
	{ item_instance = "itri_dex_strg_01", 			friendly_name = "Кольцо мощи" 						},
	{ item_instance = "itri_prot_point_01_mis", 	friendly_name = "Кольцо деревянной кожи"			},
	{ item_instance = "itri_valentinosring", 		friendly_name = "Кольцо Валентино"	 				},
	{ item_instance = "itri_orcelitering", 			friendly_name = "Кольцо элитного орка"			 	},
	{ item_instance = "itru_teleportxardas", 		friendly_name = "Руна телепорта к Ксардасу"			},
	{ item_instance = "itru_teleportfarm", 			friendly_name = "Руна телепорта к ферме"			},
	{ item_instance = "itru_teleportmonastery", 	friendly_name = "Руна телепорта к монастырю" 		},
	{ item_instance = "itru_teleportseaport",		friendly_name = "Руна телепорта в порт"			 	},
	{ item_instance = "itru_teleportpassnw", 		friendly_name = "Руна телепорта к проходу в Хоринис"},
	{ item_instance = "itru_teleporttaverne", 		friendly_name = "Руна телепорта к таверне" 			},
	{ item_instance = "itru_palteleportsecret", 	friendly_name = "Руна телепорта в секретное место"	},
	{ item_instance = "itru_teleportoc", 			friendly_name = "Руна телепорта к замку" 			},
	{ item_instance = "itru_teleportpassow", 		friendly_name = "Руна телепорта к проходу в Долину" },
	{ item_instance = "itru_teleportowdemontower", 	friendly_name = "Руна телепорта в башню демона"		},
	{ item_instance = "itsc_pallight", 				friendly_name = "Свиток света"	 					},
	{ item_instance = "itsc_pallightheal", 			friendly_name = "Свиток легкого исцеления"			},
	{ item_instance = "itsc_palmediumheal", 		friendly_name = "Свиток среднего исцеления"			},
	{ item_instance = "itsc_palfullheal", 			friendly_name = "Свиток полного исцеления"			},
	{ item_instance = "itsc_palrepelevil", 			friendly_name = "Свиток изгнания демонов"			},
	{ item_instance = "itsc_paldestroyevil", 		friendly_name = "Свиток уничтожения зла"			},
	{ item_instance = "itsc_palholybolt", 			friendly_name = "Святая стрела" 					},
	{ item_instance = "itsc_light", 				friendly_name = "Свиток света"						},
	{ item_instance = "itsc_firebolt", 				friendly_name = "Огненная стрела" 					},
	{ item_instance = "itsc_icebolt", 				friendly_name = "Ледянная стрела"					},
	{ item_instance = "itsc_lightheal", 			friendly_name = "Лечение легких ран" 				},
	{ item_instance = "itsc_mediumheal", 			friendly_name = "Лечение средних ран"	 			},
	{ item_instance = "itsc_fullheal", 				friendly_name = "Лечение тяжелых ран"	 			},
	{ item_instance = "itsc_instantfireball", 		friendly_name = "Огненный шар" 						},
	{ item_instance = "itsc_chargefireball", 		friendly_name = "Большой огненный шар"				},
	{ item_instance = "itsc_zap", 					friendly_name = "Стрела молнии" 					},
	{ item_instance = "itsc_sumwolf", 				friendly_name = "Призыв волка"  					},
	{ item_instance = "itsc_sumgobskel", 			friendly_name = "Призыв скелета-гоблина"	 		},
	{ item_instance = "itsc_sumskel", 				friendly_name = "Призыв скелета"	 				},
	{ item_instance = "itsc_sumgol", 				friendly_name = "Призыв голема" 					},
	{ item_instance = "itsc_sumdemon", 				friendly_name = "Призыв демона"		 				},
	{ item_instance = "itsc_windfist", 				friendly_name = "Кулак ветра" 						},
	{ item_instance = "itsc_sleep", 				friendly_name = "Сон" 								},
	{ item_instance = "itsc_charm", 				friendly_name = "Забвение" 							},
	{ item_instance = "itsc_lightningflash", 		friendly_name = "Удар молнии" 						},
	{ item_instance = "itsc_fear", 					friendly_name = "Страх" 							},
	{ item_instance = "itsc_icecube", 				friendly_name = "Глыба льда" 						},
	{ item_instance = "itsc_thunderball", 			friendly_name = "Шаровая молния" 					},
	{ item_instance = "itsc_harmundead", 			friendly_name = "Уничтожение нежити"	 			},
	{ item_instance = "itsc_firestorm", 			friendly_name = "Малая огненная буря" 				},
	{ item_instance = "itsc_pyrokinesis", 			friendly_name = "Большая огненная буря"				},
	{ item_instance = "itsc_icewave", 				friendly_name = "Ледянная волна"					},
	{ item_instance = "itsc_firerain", 				friendly_name = "Огненный дождь"					},
	{ item_instance = "itsc_breathofdeath", 		friendly_name = "Дыхание смерти"	 				},
	{ item_instance = "itsc_massdeath", 			friendly_name = "Волна смерти"	 					},
	{ item_instance = "itsc_armyofdarkness", 		friendly_name = "Армия тьмы" 						},
	{ item_instance = "itsc_shrink", 				friendly_name = "Уменьшение монстра" 				},
	{ item_instance = "itsc_trfsheep", 				friendly_name = "Превращение в овцу"				},
	{ item_instance = "itsc_trfscavenger", 			friendly_name = "Превращение в падальщика" 			},
	{ item_instance = "itsc_trfgiantrat", 			friendly_name = "Превращение в гигантскую крысу" 	},
	{ item_instance = "itsc_trfgiantbug", 			friendly_name = "Превращение в полевого хищника"	},
	{ item_instance = "itsc_trfwolf", 				friendly_name = "Превращение в волка" 				},
	{ item_instance = "itsc_trfwaran", 				friendly_name = "Превращение в варана"	 			},
	{ item_instance = "itsc_trfsnapper", 			friendly_name = "Превращение в снеппера"			},
	{ item_instance = "itsc_trfwarg", 				friendly_name = "Превращение в варга" 				},
	{ item_instance = "itsc_trffirewaran", 			friendly_name = "Превращение в огненного варана" 	},
	{ item_instance = "itsc_trflurker", 			friendly_name = "Превращение в луркера"				},
	{ item_instance = "itsc_trfshadowbeast", 		friendly_name = "Превращение в мракориса" 			},
	{ item_instance = "itsc_trfdragonsnapper", 		friendly_name = "Превращение в драконнего снеппера"	},
	{ item_instance = "itmi_runeblank", 			friendly_name = "Пустая руна" 						},
	{ item_instance = "itru_light", 				friendly_name = "Руна света" 						},
	{ item_instance = "itru_zap", 					friendly_name = "Руна стрелы молнии"				},
	{ item_instance = "itru_firebolt", 				friendly_name = "Руна огненная стрела" 				},
	{ item_instance = "itru_icebolt", 				friendly_name = "Руна ледянная стрела" 				},
	{ item_instance = "itru_icewave", 				friendly_name = "Руна ледянная волна"				},
	{ item_instance = "itru_windfist", 				friendly_name = "Руна кулак ветра"					},
	{ item_instance = "itru_sleep", 				friendly_name = "Руна сон"							},
	{ item_instance = "itru_lightheal", 			friendly_name = "Руна исцеления легких ран"			},
	{ item_instance = "itru_mediumheal", 			friendly_name = "Руна исцеления средних ран"		},
	{ item_instance = "itru_fullheal", 				friendly_name = "Руна полного исцеления" 			},
	{ item_instance = "itru_firerain", 				friendly_name = "Руна огненный дождь"				},
	{ item_instance = "itru_lightningflash", 		friendly_name = "Руна удар молнии"					},
	{ item_instance = "itru_instantfireball", 		friendly_name = "Руна огненный шар"					},
	{ item_instance = "itru_chargefireball", 		friendly_name = "Руна большой огненный шар"			},
	{ item_instance = "itru_fear", 					friendly_name = "Руна страха"						},
	{ item_instance = "itru_icecube", 				friendly_name = "Руна ледянная глыба"				},
	{ item_instance = "itru_thunderball", 			friendly_name = "Руна шаровая молния"				},
	{ item_instance = "itru_harmundead", 			friendly_name = "Руна изгнание нежити" 				},
	{ item_instance = "itru_firestorm", 			friendly_name = "Руна малая огненная буря"			},
	{ item_instance = "itru_pyrokinesis", 			friendly_name = "Руна большая огненная буря"		},
	{ item_instance = "itru_sumgobskel", 			friendly_name = "Руна призыва гоблинка-скелета"		},
	{ item_instance = "itru_sumwolf", 				friendly_name = "Руна призыва волка"				},
	{ item_instance = "itru_sumskel", 				friendly_name = "Руна призыва скелета" 				},
	{ item_instance = "itru_sumgol", 				friendly_name = "Руна призыва голема"				},
	{ item_instance = "itru_sumdemon", 				friendly_name = "Руна призыва демона" 				},
	{ item_instance = "itru_armyofdarkness",		friendly_name = "Руна армия тьмы" 					},
	{ item_instance = "itru_breathofdeath", 		friendly_name = "Руна дыхание смерти" 				},
	{ item_instance = "itru_massdeath", 			friendly_name = "Руна волна смерти"					},
	{ item_instance = "itru_masterofdisaster", 		friendly_name = "Руна разрушения" 					},
	{ item_instance = "itru_shrink", 				friendly_name = "Руна уменьшение монстра"			},
	{ item_instance = "itru_deathbolt", 			friendly_name = "Руна стрела смерти" 				},
	{ item_instance = "itru_concussionbolt", 		friendly_name = "Руна стрела сотрясения" 			},
	{ item_instance = "itru_pallight", 				friendly_name = "Руна святой свет" 					},
	{ item_instance = "itru_pallightheal", 			friendly_name = "Руна легкое исцеление"				},
	{ item_instance = "itru_palmediumheal", 		friendly_name = "Руна среднее исцеление"			},
	{ item_instance = "itru_palfullheal", 			friendly_name = "Руна полное исцеление"				},
	{ item_instance = "itru_palholybolt", 			friendly_name = "Руна святая стрела"				},
	{ item_instance = "itru_palrepelevil", 			friendly_name = "Руна изгнание демонов"				},
	{ item_instance = "itru_paldestroyevil", 		friendly_name = "Руна уничтожение зла"				},
	{ item_instance = "itpl_weed", 					friendly_name = "Сорняк" 							},
	{ item_instance = "itpl_beet", 					friendly_name = "Репа" 								},
	{ item_instance = "itpl_strenght_herb_01", 		friendly_name = "Драконний корень" 					},
	{ item_instance = "itpl_speed_herb_01", 		friendly_name = "Снеппер трава"						},
	{ item_instance = "itpl_dex_herb_01", 			friendly_name = "Ягода гоблина" 					},
	{ item_instance = "itpl_temp_herb", 			friendly_name = "Орочья трава" 						},
	{ item_instance = "itpl_forestberry", 			friendly_name = "Лесная ягода" 						},
	{ item_instance = "itpl_swampherb", 			friendly_name = "Болотник"		 					},
	{ item_instance = "itpl_blueplant", 			friendly_name = "Синяя бузина"	 					},
	{ item_instance = "itpo_health_01", 			friendly_name = "Эссенция лечения" 					},
	{ item_instance = "itpo_health_02", 			friendly_name = "Экстракт лечения"	 				},
	{ item_instance = "itpo_mana_01", 				friendly_name = "Эссенция маны" 					},
	{ item_instance = "itpo_mana_02", 				friendly_name = "Экстракт маны" 					},
	{ item_instance = "itpo_mana_03", 				friendly_name = "Эликсир маны" 						},
	{ item_instance = "itpo_perm_str", 				friendly_name = "Эликсир силы" 						},
	{ item_instance = "itpo_perm_dex", 				friendly_name = "Эликсир ловкости"	 				},
	{ item_instance = "itpo_perm_health", 			friendly_name = "Эликсир здоровья(вечн)"			},
	{ item_instance = "itpo_perm_mana", 			friendly_name = "Эликсир маны(вечн)"				},
	{ item_instance = "itpo_speed", 				friendly_name = "Микстура скорости" 				},
	{ item_instance = "itpo_perm_littlemana", 		friendly_name = "Эссенция маны(вечн)"				},
	{ item_instance = "itpo_healhilda_mis", 		friendly_name = "Зелье Хильды" 						},
	{ item_instance = "itpo_healobsession_mis", 	friendly_name = "Излечение одержимости"				},
	{ item_instance = "itpo_healrandolph_mis", 		friendly_name = "Зелье Рэндольфа"	 				},
	{ item_instance = "itpo_dragoneggdrinkneoras_mis", friendly_name = "Эссенция драконнего яйца"		},
	{ item_instance = "itpo_megadrink", 			friendly_name = "Сильный напиток" 					},
	{ item_instance = "itpo_potionofdeath_01_mis", 	friendly_name = "Слезы Инноса(эффект неизвестен)"	},
	{ item_instance = "itpo_potionofdeath_02_mis", 	friendly_name = "Слезы Инноса(эффект известен)"		},
	{ item_instance = "itke_lockpick", 				friendly_name = "Отмычка" 							},
	{ item_instance = "itke_valentino", 			friendly_name = "Ключ от сундука Валентино"			},
	{ item_instance = "itke_dexter", 				friendly_name = "Ключ от сундука Декстера" 			},
	{ item_instance = "itke_xardas", 				friendly_name = "Ключ от сундука в башне Ксардаса"	},
	{ item_instance = "itke_magicchest", 			friendly_name = "Старый железный ключ" 				},
	{ item_instance = "itke_fingers", 				friendly_name = "Ключ к двери из каналов" 			},
	{ item_instance = "itke_hotel", 				friendly_name = "Ключ от подвала гостинницы" 		},
	{ item_instance = "itke_city_tower_01",			friendly_name = "Ключ от башни города #1"		 	},
	{ item_instance = "itke_city_tower_02",			friendly_name = "Ключ от башни города #2"		 	},
	{ item_instance = "itke_city_tower_03", 		friendly_name = "Ключ от башни города #3"		 	},
	{ item_instance = "itke_city_tower_04", 		friendly_name = "Ключ от башни города #4"		 	},
	{ item_instance = "itke_city_tower_05",			friendly_name = "Ключ от башни города #5"		 	},
	{ item_instance = "itke_city_tower_06", 		friendly_name = "Ключ от башни города #6"		 	},
	{ item_instance = "itke_key_01", 				friendly_name = "Ключ 1" 							},
	{ item_instance = "itke_key_02", 				friendly_name = "Ключ 2" 							},
	{ item_instance = "itke_key_03", 				friendly_name = "Ключ 3" 							},
	{ item_instance = "itmw_1h_vlk_dagger", 		friendly_name = "Кинжал" 							},
	{ item_instance = "itmw_1h_bau_axe", 			friendly_name = "Серп" 								},
	{ item_instance = "itmw_malethsgehstock_mis", 	friendly_name = "Палка" 							},
	{ item_instance = "itmw_1h_vlk_axe", 			friendly_name = "Топор" 							},
	{ item_instance = "itmw_1h_bau_mace", 			friendly_name = "Тяжелая палка"						},
	{ item_instance = "itmw_shortsword1", 			friendly_name = "Короткий меч"		 				},
	{ item_instance = "itmw_sense", 				friendly_name = "Малая коса" 						},
	{ item_instance = "itmw_alrikssword_mis", 		friendly_name = "Меч Альрика" 						},
	{ item_instance = "itmw_shortsword2", 			friendly_name = "Грубый короткий меч" 				},
	{ item_instance = "itmw_1h_sword_l_03", 		friendly_name = "Волчий нож" 						},
	{ item_instance = "itmw_nagelknueppel", 		friendly_name = "Дубина с шипами"	 				},
	{ item_instance = "itmw_1h_misc_sword", 		friendly_name = "Ржавый меч"			 			},
	{ item_instance = "itmw_shortsword3", 			friendly_name = "Короткий меч" 						},
	{ item_instance = "itmw_1h_vlk_sword", 			friendly_name = "Меч" 								},
	{ item_instance = "itmw_nagelkeule", 			friendly_name = "Палка с шипами" 					},
	{ item_instance = "itmw_shortsword4", 			friendly_name = "Короткий меч" 						},
	{ item_instance = "itmw_kriegskeule", 			friendly_name = "Боевой посох" 						},
	{ item_instance = "itmw_1h_sld_axe", 			friendly_name = "Грубый тесак"	 					},
	{ item_instance = "itmw_1h_mil_sword", 			friendly_name = "Грубый широкий меч"	 			},
	{ item_instance = "itmw_alrikssword_mis", 		friendly_name = "Меч Альрика" 						},
	{ item_instance = "itmw_shortsword5",			friendly_name = "Благородный короткий меч"			},
	{ item_instance = "itmw_richtstab", 			friendly_name = "Посох судьи"	 					},
	{ item_instance = "itmw_1h_sld_sword", 			friendly_name = "Грубый меч"	 					},
	{ item_instance = "itmw_kriegshammer1", 		friendly_name = "Военный молот"						},
	{ item_instance = "itmw_nagelkeule2", 			friendly_name = "Грубая дубина с шипами" 			},
	{ item_instance = "itmw_schwert", 				friendly_name = "Грубый длинный меч" 				},
	{ item_instance = "itmw_piratensaebel", 		friendly_name = "Пиратская сабля" 					},
	{ item_instance = "itmw_schiffsaxt", 			friendly_name = "Абордажный топор" 					},
	{ item_instance = "itmw_1h_common_01", 			friendly_name = "Кованный меч"				 		},
	{ item_instance = "itmw_1h_pal_sword", 			friendly_name = "Меч паладина"	 					},
	{ item_instance = "itmw_schwert1", 				friendly_name = "Благородный меч"					},
	{ item_instance = "itmw_steinbrecher", 			friendly_name = "Дробитель камней"					},
	{ item_instance = "itmw_spicker",				friendly_name = "Раскалыватель черепов"				},
	{ item_instance = "itmw_schwert2", 				friendly_name = "Длинный меч"						},
	{ item_instance = "itmw_bartaxt", 				friendly_name = "Бердыш"	 						},
	{ item_instance = "itmw_doppelaxt", 			friendly_name = "Двойной топор" 					},
	{ item_instance = "itmw_schwert3", 				friendly_name = "Грубый полуторный меч" 			},
	{ item_instance = "itmw_schwert4", 				friendly_name = "Благородный длинный меч"			},
	{ item_instance = "itmw_morgenstern", 			friendly_name = "Булава с шипами" 					},
	{ item_instance = "itmw_1h_special_01", 		friendly_name = "Длинный рудный меч" 				},
	{ item_instance = "itmw_streitkolben", 			friendly_name = "Булава" 							},
	{ item_instance = "itmw_rubinklinge", 			friendly_name = "Рубиновый клинок" 					},
	{ item_instance = "itmw_rapier", 				friendly_name = "Рапира" 							},
	{ item_instance = "itmw_runenschwert", 			friendly_name = "Рунный меч"	 					},
	{ item_instance = "itmw_schwert5", 				friendly_name = "Изысканный полуторный меч" 		},
	{ item_instance = "itmw_rabenschnabel", 		friendly_name = "Клюв ворона" 						},
	{ item_instance = "itmw_inquisitor", 			friendly_name = "Инквизитор" 						},
	{ item_instance = "itmw_1h_special_02", 		friendly_name = "Рудный полуторный меч"		 		},
	{ item_instance = "itmw_1h_blessed_01", 		friendly_name = "Грубый рудный клинок"	 			},
	{ item_instance = "itmw_1h_ferrossword_mis", 	friendly_name = "Меч Фероса" 						},
	{ item_instance = "itmw_orkschlaechter", 		friendly_name = "Убийца орков" 						},
	{ item_instance = "itmw_kriegshammer2", 		friendly_name = "Тяжелый военный молот"				},
	{ item_instance = "itmw_folteraxt", 			friendly_name = "Топор палача"	 					},
	{ item_instance = "itmw_elbastardo", 			friendly_name = "Эль бастардо" 						},
	{ item_instance = "itmw_meisterdegen", 			friendly_name = "Шпага мастера"		 				},
	{ item_instance = "itmw_1h_blessed_02", 		friendly_name = "Освященный рудный клинок"		 	},
	{ item_instance = "itmw_1h_special_03", 		friendly_name = "Боевой клинок орков"	 			},
	{ item_instance = "itmw_1h_blessed_03", 		friendly_name = "Гнев Инноса" 						},
	{ item_instance = "itmw_1h_special_04", 		friendly_name = "Рудный клинок убийца драконов"		},
	{ item_instance = "itmw_2h_axe_l_01", 			friendly_name = "Кирка"								},
	{ item_instance = "itmw_2h_bau_axe", 			friendly_name = "Топор дровосека"					},
	{ item_instance = "itmw_1h_nov_mace", 			friendly_name = "Боевой посох"						},
	{ item_instance = "itmw_2h_sword_m_01", 		friendly_name = "Ржавый двуручник"			 		},
	{ item_instance = "itmw_1h_misc_axe", 			friendly_name = "Ржавый топор"		 				},
	{ item_instance = "itmw_2h_sld_sword", 			friendly_name = "Грубый двуручник"		 			},
	{ item_instance = "itmw_zweihaender1", 			friendly_name = "Легкий двуручник"		 			},
	{ item_instance = "itmw_zweihaender2", 			friendly_name = "Двуручный меч" 					},
	{ item_instance = "itmw_zweihaender3", 			friendly_name = "Сила рун"	 						},
	{ item_instance = "itmw_zweihaender4", 			friendly_name = "Тяжелый двуручный меч" 			},
	{ item_instance = "itmw_hellebarde", 			friendly_name = "Алебарда"	 						},
	{ item_instance = "itmw_stabkeule", 			friendly_name = "Палица"		 					},
	{ item_instance = "itmw_2h_orcaxe_01", 			friendly_name = "Легкий топор орков" 				},
	{ item_instance = "itmw_2h_orcaxe_02", 			friendly_name = "Средний топор орков" 				},
	{ item_instance = "itmw_2h_orcaxe_03", 			friendly_name = "Тяжелый топор орков" 				},
	{ item_instance = "itmw_2h_orcaxe_04", 			friendly_name = "Огромный топор орков" 				},
	{ item_instance = "itmw_2h_orcsword_01", 		friendly_name = "Меч ящера"					 		},
	{ item_instance = "itmw_2h_orcsword_02", 		friendly_name = "Меч элитного орка" 				},
	{ item_instance = "itmw_2h_sld_sword", 			friendly_name = "Грубый двуручный меч"	 			},
	{ item_instance = "itmw_streitaxt1", 			friendly_name = "Легкий боевой топор" 				},
	{ item_instance = "itmw_streitaxt2", 			friendly_name = "Боевой топор" 						},
	{ item_instance = "itmw_2h_sld_axe", 			friendly_name = "Грубый боевой топор" 				},
	{ item_instance = "itmw_2h_pal_sword", 			friendly_name = "Двуручный меч паладина" 			},
	{ item_instance = "itmw_2h_special_01", 		friendly_name = "Двуручный рудный меч"	 			},
	{ item_instance = "itmw_2h_special_02", 		friendly_name = "Тяжелый рудный клинок"			 	},
	{ item_instance = "itmw_2h_special_03", 		friendly_name = "Тяжелый рудный боевой клинок"	 	},
	{ item_instance = "itmw_2h_special_04", 		friendly_name = "Большой рудный меч убийца драконов"},
	{ item_instance = "itmw_2h_blessed_01", 		friendly_name = "Грубый рудный клинок"	 			},
	{ item_instance = "itmw_2h_blessed_02", 		friendly_name = "Меч ордена" 						},
	{ item_instance = "itmw_2h_blessed_03", 		friendly_name = "Святой палач" 						},
	{ item_instance = "itmw_krummschwert", 			friendly_name = "Абордажная сабля"					},
	{ item_instance = "itmw_schlachtaxt", 			friendly_name = "Военный топор" 					},
	{ item_instance = "itmw_sturmbringer", 			friendly_name = "Несущий бурю"						},
	{ item_instance = "itmw_barbarenstreitaxt", 	friendly_name = "Боевой топор варвара"		 		},
	{ item_instance = "itmw_berserkeraxt", 			friendly_name = "Топор берсеркера" 					},
	{ item_instance = "itmw_drachenschneide", 		friendly_name = "Гроза драконов"					},
	{ item_instance = "holy_hammer_mis", 			friendly_name = "Святой молот" 						},
	{ item_instance = "itrw_sld_bow", 				friendly_name = "Лук" 								},
	{ item_instance = "itrw_bow_l_01", 				friendly_name = "Короткий лук" 						},
	{ item_instance = "itrw_bow_l_02", 				friendly_name = "Ивовый лук"	 					},
	{ item_instance = "itrw_bow_l_03", 				friendly_name = "Охотничий лук" 					},
	{ item_instance = "itrw_bow_l_04", 				friendly_name = "Вязовый лук" 						},
	{ item_instance = "itrw_bow_m_01", 				friendly_name = "Композитный лук" 					},
	{ item_instance = "itrw_bow_m_02",				friendly_name = "Ясеневый лук"	 					},
	{ item_instance = "itrw_bow_m_03", 				friendly_name = "Длинный лук" 						},
	{ item_instance = "itrw_bow_m_04", 				friendly_name = "Буковый лук" 						},
	{ item_instance = "itrw_bow_h_01", 				friendly_name = "Костяной лук" 						},
	{ item_instance = "itrw_bow_h_02", 				friendly_name = "Дубовый лук" 						},
	{ item_instance = "itrw_bow_h_03", 				friendly_name = "Военный лук" 						},
	{ item_instance = "itrw_bow_h_04", 				friendly_name = "Драконий лук" 						},
	{ item_instance = "itrw_mil_crossbow", 			friendly_name = "Арбалет(урон 20)"					},
	{ item_instance = "itrw_crossbow_l_01", 		friendly_name = "Охотничий арбалет"					},
	{ item_instance = "itrw_crossbow_l_02", 		friendly_name = "Легкий арбалет"					},
	{ item_instance = "itrw_crossbow_m_01", 		friendly_name = "Арбалет(урон 55)" 					},
	{ item_instance = "itrw_crossbow_m_02", 		friendly_name = "Боевой арбалет"					},
	{ item_instance = "itrw_dragomirsarmbrust_mis", friendly_name = "Арбалет Драгомира"					},
	{ item_instance = "itrw_sengrathsarmbrust_mis", friendly_name = "Арбалет Сенграта" 					},
	{ item_instance = "itrw_crossbow_h_01", 		friendly_name = "Тяжелый арбалет"					},
	{ item_instance = "itrw_crossbow_h_02", 		friendly_name = "Арбалет охотника на драконов"		},
	{ item_instance = "itar_vlk_l",					friendly_name = "Одежда горожанина 1" 				},
	{ item_instance = "itar_vlk_m", 				friendly_name = "Одежда горожанина 2" 				},
	{ item_instance = "itar_vlk_h", 				friendly_name = "Одежда горожанина 3" 				},
	{ item_instance = "itar_vlkbabe_l", 			friendly_name = "Одежда горожанки 1" 				},
	{ item_instance = "itar_vlkbabe_m", 			friendly_name = "Одежда горожанки 2" 				},
	{ item_instance = "itar_vlkbabe_h", 			friendly_name = "Одежда горожанки 3" 				},
	{ item_instance = "itar_bau_l", 				friendly_name = "Одежда крестьянина 1"				},
	{ item_instance = "itar_bau_m", 				friendly_name = "Одежда крестьянина 2"				},
	{ item_instance = "itar_baubabe_l", 			friendly_name = "Одежда крестьянки 1"				},
	{ item_instance = "itar_baubabe_m", 			friendly_name = "Одежда крестьянки 2"				},
	{ item_instance = "itar_prisoner", 				friendly_name = "Штаны рудокопа" 					},
	{ item_instance = "itar_barkeeper", 			friendly_name = "Одежда трактирщика"				},
	{ item_instance = "itar_smith", 				friendly_name = "Одежда кузнеца"					},
	{ item_instance = "itar_judge", 				friendly_name = "Одежда судьи"	 					},
	{ item_instance = "itar_governor", 				friendly_name = "Дублет губернатора" 				},
	{ item_instance = "itar_leather_l", 			friendly_name = "Кожаный доспех" 					},
	{ item_instance = "itar_bdt_m", 				friendly_name = "Средний доспех бандита" 			},
	{ item_instance = "itar_bdt_h", 				friendly_name = "Тяжелый доспех бандита" 			},
	{ item_instance = "itar_mil_l", 				friendly_name = "Легкий доспех ополченца"			},
	{ item_instance = "itar_mil_m", 				friendly_name = "Тяжелый доспех ополченца" 			},
	{ item_instance = "itar_pal_m", 				friendly_name = "Доспех паладина"					},
	{ item_instance = "itar_pal_h", 				friendly_name = "Броня паладина" 					},
	{ item_instance = "itar_djg_crawler", 			friendly_name = "Доспех из пластин ползунов" 		},
	{ item_instance = "itar_sld_l", 				friendly_name = "Легкий доспех наемника" 			},
	{ item_instance = "itar_sld_m", 				friendly_name = "Средний доспех наемника" 			},
	{ item_instance = "itar_sld_h", 				friendly_name = "Тяжелый доспех наемника" 			},
	{ item_instance = "itar_djg_l", 				friendly_name = "Легкая броня охотника на драконов"	},
	{ item_instance = "itar_djg_m", 				friendly_name = "Средняя броня охотника на драконов"},
	{ item_instance = "itar_djg_h", 				friendly_name = "Тяжелая броня охотника на драконов"},
	{ item_instance = "itar_djg_babe", 				friendly_name = "Женская броня охотника на драконов"},
	{ item_instance = "itar_nov_l", 				friendly_name = "Одежда послушника"					},
	{ item_instance = "itar_kdf_l", 				friendly_name = "Одеяние мага огня"					},
	{ item_instance = "itar_kdf_h", 				friendly_name = "Одеяние магистра огня" 			},
	{ item_instance = "itar_kdw_h", 				friendly_name = "Одеяние магистра воды"				},
	{ item_instance = "itar_dementor",				friendly_name = "Одеяние ищущего" 					},
	{ item_instance = "itar_lester", 				friendly_name = "Доспех Лестера"		 			},
	{ item_instance = "itar_diego", 				friendly_name = "Броня Диего"	 					},
	{ item_instance = "itar_corangar", 				friendly_name = "Броня Ангара"				 		},
	{ item_instance = "itar_xardas", 				friendly_name = "Одеяние магистра тьмы"				},
	{ item_instance = "itar_pal_skel", 				friendly_name = "Старый доспех паладина" 			},
	{ item_instance = "itam_addon_franco", 			friendly_name = "Амулет Франко" 					},
	{ item_instance = "itam_addon_health", 			friendly_name = "Амулет здоровья"	 				},
	{ item_instance = "itam_addon_mana", 			friendly_name = "Амулет маны" 						},
	{ item_instance = "itam_addon_str", 			friendly_name = "Амулет силы"	 					},
	{ item_instance = "itam_addon_wispdetecr", 		friendly_name = "Амулет защиты от огня"		 		},
	{ item_instance = "itrw_bolt", 					friendly_name = "Болт" 								},
	{ item_instance = "itrw_arrow", 				friendly_name = "Стрела" 							},
	{ item_instance = "itrw_addon_magicarrow", 		friendly_name = "Магическая стрела"					},
	{ item_instance = "itrw_addon_magicbolt", 		friendly_name = "Магический болт"		 			},
	{ item_instance = "itrw_addon_firearrow", 		friendly_name = "Огненная стрела"					},
	{ item_instance = "itmw_addon_pir1hsword", 		friendly_name = "Абордажный нож"					},
	{ item_instance = "itmw_addon_stab01", 			friendly_name = "Посох мага" 						},
	{ item_instance = "itmw_addon_stab04", 			friendly_name = "Посох магов воды" 					},
	{ item_instance = "itmw_addon_hacker_1h_01", 	friendly_name = "Мачете" 							},
	{ item_instance = "itmw_addon_stab02", 			friendly_name = "Магический посох" 					},
	{ item_instance = "itmw_addon_pir2haxe", 		friendly_name = "Пиратский топор"					},
	{ item_instance = "itmw_addon_betty", 			friendly_name = "Бетти"		 						},
	{ item_instance = "itmw_1h_sword_l_03", 		friendly_name = "Нож"								},
	{ item_instance = "itmw_addon_bandittrader", 	friendly_name = "Рапира бандита" 					},
	{ item_instance = "itmw_rangerstaff_addon", 	friendly_name = "Боевой посох кольца воды"	 		},
	{ item_instance = "itmw_addon_keule_2h_01", 	friendly_name = "Слуга бури" 						},
	{ item_instance = "itmw_addon_keule_1h_01", 	friendly_name = "Слуга ветра" 						},
	{ item_instance = "itmw_addon_hacker_1h_02", 	friendly_name = "Старое мачете" 					},
	{ item_instance = "itmw_addon_hacker_2h_02", 	friendly_name = "Старое гигантское мачете"			},
	{ item_instance = "itmw_addon_stab05", 			friendly_name = "Тайфун" 							},
	{ item_instance = "itmw_addon_pir1haxe", 		friendly_name = "Корабельный топор"					},
	{ item_instance = "itmw_addon_hacker_2h_01", 	friendly_name = "Огромное мачете" 					},
	{ item_instance = "itmw_addon_stab03", 			friendly_name = "Посох магов воды"					},
	{ item_instance = "itmw_francisdagger_mis", 	friendly_name = "Хороший кинжал" 					},
	{ item_instance = "itfo_addon_rum", 			friendly_name = "Ром" 								},
	{ item_instance = "itfo_addon_grog", 			friendly_name = "Грог" 								},
	{ item_instance = "itfo_addon_krokofleisch_mission", friendly_name = "Мясо болотной крысы"		 	},
	{ item_instance = "itfo_addon_firestew", 		friendly_name = "Пламенная нарезка"					},
	{ item_instance = "itfo_addon_shellflesh", 		friendly_name = "Мясо моллюска"						},
	{ item_instance = "itfo_addon_meatsoup", 		friendly_name = "Мясной суп"	 					},
	{ item_instance = "itke_canyonlibrary_hierarchy_books_addon", friendly_name = "Ключ от библиотеки в каньоне" },
	{ item_instance = "itke_greg_addon_mis", 		friendly_name = "Ключ от дома Грега" 				},
	{ item_instance = "itke_portaltempelwalkthrough_addon", friendly_name = "Ключ от замка с телепортом"},
	{ item_instance = "itke_addon_buddler_01", 		friendly_name = "Ключ к ящикам в лагере бандитов"	},
	{ item_instance = "itke_addon_esteban_01", 		friendly_name = "Ключ Эстебана" 					},
	{ item_instance = "itke_addon_tavern_01", 		friendly_name = "Ключ Лу" 							},
	{ item_instance = "itke_addon_thorus", 			friendly_name = "Ключ Торуса"	 					},
	{ item_instance = "itke_addon_skinner", 		friendly_name = "Ключ Скиннера" 					},
	{ item_instance = "itke_orlan_teleportstation", friendly_name = "Ключ Орлана" 						},
	{ item_instance = "itpo_mana_addon_04", 		friendly_name = "Чистая мана" 						},
	{ item_instance = "itpo_health_addon_04", 		friendly_name = "Чистое здоровье"					},
	{ item_instance = "itpo_addon_geist_02", 		friendly_name = "Зелье изменения сознания"			},
	{ item_instance = "itpo_addon_geist_01", 		friendly_name = "Зелье изменения сознания"			},
	{ item_instance = "itrw_addon_magiccrossbow", 	friendly_name = "Магический арбалет"				},
	{ item_instance = "itrw_addon_magicbow", 		friendly_name = "Магический лук"					},
	{ item_instance = "itrw_addon_firebow", 		friendly_name = "Огненный лук" 						},
	{ item_instance = "itmi_iedrum", 				friendly_name = "Барабан" 							},
	{ item_instance = "itmi_addon_whitepearl", 		friendly_name = "Жемчужина" 						},
	{ item_instance = "itmi_goldnugget_addon", 		friendly_name = "Золотой самородок"					},
	{ item_instance = "itmi_skull", 				friendly_name = "Череп" 							},
	{ item_instance = "itmi_ieharfe", 				friendly_name = "Арфа" 								},
	{ item_instance = "itse_addon_cavalornsbeutel", friendly_name = "Мешочек Кавалорна"		 			},
	{ item_instance = "itmi_bromorsgeld_addon", 	friendly_name = "Золотая чаша Бромора" 				},
	{ item_instance = "itmi_baltrampaket", 			friendly_name = "Пакет Бальтрама" 					},
	{ item_instance = "itru_geyser", 				friendly_name = "Руна гейзер"						},
	{ item_instance = "itru_suckenergy", 			friendly_name = "Руна кража энергии"				},
	{ item_instance = "itru_icelance", 				friendly_name = "Руна ледяное копье"				},
	{ item_instance = "itru_skull_rune", 			friendly_name = "Руна череп"						},
	{ item_instance = "itru_beliarsrage",			friendly_name = "Руна ярость Белиара"				},
	{ item_instance = "itar_kdw_l_addon", 			friendly_name = "Одеяние мага воды"					},
	{ item_instance = "itar_firearmor_addon", 		friendly_name = "Огненная броня" 					},
	{ item_instance = "itar_pir_m_addon", 			friendly_name = "Пиратская броня" 					},
	{ item_instance = "itar_pir_l_addon", 			friendly_name = "Пиратский доспех"	 				},
	{ item_instance = "itar_mayazombie_addon", 		friendly_name = "Ржавая броня Равена"				},
	{ item_instance = "itar_pir_h_addon", 			friendly_name = "Доспех капитана" 					},
	{ item_instance = "itar_bloodwyn_addon", 		friendly_name = "Доспех Бладвина" 					},
	{ item_instance = "itar_thorus_addon", 			friendly_name = "Доспех Торуса"			 			},
	{ item_instance = "itar_raven_addon", 			friendly_name = "Доспех Равена"						},
}

function GetItemName( item_instance )
	if item_instance and type( item_instance ) == "string" then
		for key, item in ipairs( inst_Items ) do
			if( string.lower( item_instance ) == item.item_instance ) then
				return item.friendly_name
			end
		end
	end
	return item_instance
end

function GetRusItemName( friendly_name )
	if friendly_name and type( friendly_name ) == "string" then
		for key, item in ipairs( inst_Items ) do
			if( string.lower( friendly_name ) == item.friendly_name ) then
				return item.item_instance
			end
		end
	end
	return friendly_name
end